spring:
  datasource:
    name: mss_provider
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mss
    username: root
    password:
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      initial-size: 5
      max-active: 20
      max-wait: 5000
      min-idle: 5
  flyway:
    enabled: true
management:
  endpoint:
    health:
      show-details: always

aws:
  region: ${AWS_DEFAULT_REGION}
  secrets-manager:
    enabled: true
    mysql-secret-name: rds/mysql/mss