spring:
  datasource:
    name: mss-provider
    url: "jdbc:h2:mem:mss_provider;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS mss_provider\\;SET SCHEMA mss_provider"
    driver-class-name: org.h2.Driver